// packages/control-plane-ui/src/apps/control-plane/story/StoryDecisionAnswer.vue
<template>
  <div class="story-decision-answer">
    <div class="story-decision-choices" role="radiogroup" :aria-label="decision.question">
      <button
        v-for="(option, index) in decision.options"
        :key="option.id"
        type="button"
        role="radio"
        class="story-decision-choice"
        :aria-checked="selectedOptionId === option.id"
        :disabled="disabled || busy"
        @click="chooseOption(option.id)"
        @keydown="handleChoiceKeydown"
      >
        <span class="story-decision-choice-index" aria-hidden="true">{{ index + 1 }}</span>
        <span class="story-decision-choice-label">{{ option.label }}</span>
      </button>
      <button
        v-if="decision.allowFreeText"
        type="button"
        role="radio"
        class="story-decision-choice"
        :aria-checked="replySelected"
        :disabled="disabled || busy"
        @click="chooseReply"
        @keydown="handleChoiceKeydown"
      >
        <span class="story-decision-choice-index" aria-hidden="true">{{ decision.options.length + 1 }}</span>
        <span class="story-decision-choice-label">{{ t("stories.decisions.replyOption") }}</span>
      </button>
      <div v-if="replySelected" class="story-decision-reply">
        <Textarea
          v-model="response"
          class="min-h-0 resize-y text-xs"
          :placeholder="t('stories.decisions.freeTextPlaceholder')"
          :disabled="disabled || busy"
          rows="2"
        />
      </div>
    </div>
    <div class="story-decision-buttons">
      <Button variant="outline" size="sm" :disabled="disabled || busy || !canSubmit" @click="submit">
        {{ busy ? t("stories.decisions.submitting") : t("stories.decisions.submit") }}
      </Button>
      <Button variant="ghost" size="sm" :disabled="disabled || busy" @click="emit('cancel')">{{ t("stories.decisions.cancel") }}</Button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useI18n } from "vue-i18n";
import type { StoryDecision } from "@task-handoff/protocol/stories";
import { Button } from "../../../components/ui/button";
import { Textarea } from "../../../components/ui/textarea";
import type { StoryDecisionAnswerInput } from "./storyDecisionPresentation.ts";

const props = defineProps<{ decision: StoryDecision; disabled?: boolean; busy?: boolean }>();
const emit = defineEmits<{ submit: [input: StoryDecisionAnswerInput]; cancel: [] }>();
const { t } = useI18n();

const optionId = ref("");
const replyPicked = ref(false);
const response = ref("");

// 只允许自由文本的决策没有可选项，回复就是唯一答案，直接展开。
const replySelected = computed(() => replyPicked.value || (!props.decision.options.length && props.decision.allowFreeText));
const selectedOptionId = computed(() => optionId.value);
const canSubmit = computed(() => Boolean(optionId.value) || (replySelected.value && Boolean(response.value.trim())));

watch(() => props.decision.id, () => {
  optionId.value = "";
  replyPicked.value = false;
  response.value = "";
});

function chooseOption(id: string) {
  optionId.value = id;
  replyPicked.value = false;
}
function chooseReply() {
  optionId.value = "";
  replyPicked.value = true;
}
function handleChoiceKeydown(event: KeyboardEvent) {
  if (!["ArrowDown", "ArrowUp", "ArrowLeft", "ArrowRight"].includes(event.key)) return;
  const current = event.currentTarget as HTMLButtonElement;
  const group = current.closest(".story-decision-choices");
  if (!group) return;
  const choices = Array.from(group.querySelectorAll<HTMLButtonElement>('[role="radio"]:not([disabled])'));
  const index = choices.indexOf(current);
  if (index < 0 || !choices.length) return;
  event.preventDefault();
  const step = event.key === "ArrowDown" || event.key === "ArrowRight" ? 1 : -1;
  const next = choices[(index + step + choices.length) % choices.length];
  next.focus();
  next.click();
}
function submit() {
  if (!canSubmit.value || props.disabled || props.busy) return;
  emit("submit", {
    ...(optionId.value ? { optionId: optionId.value } : {}),
    ...(replySelected.value && response.value.trim() ? { response: response.value.trim() } : {}),
  });
}
</script>

<style scoped>
.story-decision-answer { display:grid; gap:8px; min-width:0; }
.story-decision-choices { display:grid; gap:2px; min-width:0; }
.story-decision-choice { display:flex; width:100%; min-height:34px; align-items:center; gap:10px; border:1px solid transparent; border-radius:7px; background:transparent; color:var(--text); cursor:pointer; font-size:12px; line-height:1.4; padding:4px 8px; text-align:left; }
.story-decision-choice:not([aria-checked="true"]):hover:not(:disabled) { background:var(--surface-hover); }
.story-decision-choice:focus-visible { outline:2px solid var(--focus-ring); outline-offset:-1px; }
.story-decision-choice[aria-checked="true"] { border-color:color-mix(in srgb,var(--brand-accent) 55%,var(--line)); background:var(--brand-accent-soft); color:var(--text-strong); }
.story-decision-choice:disabled { cursor:default; opacity:.55; }
.story-decision-choice-index { display:grid; flex:0 0 auto; width:20px; height:20px; place-items:center; border-radius:6px; background:var(--surface-active); color:var(--text-muted); font-size:11px; font-variant-numeric:tabular-nums; }
.story-decision-choice[aria-checked="true"] .story-decision-choice-index { background:var(--brand-accent); color:var(--brand-accent-foreground); }
.story-decision-choice-label { min-width:0; overflow-wrap:anywhere; }
.story-decision-reply { margin:2px 0 2px 30px; }
.story-decision-buttons { display:flex; gap:8px; }
</style>

// apps/mobile/src/stories/StoryDecisionAnswer.tsx
import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import type { StoryDecision } from '@task-handoff/protocol/stories';

import { useMobileTheme } from '../components/theme';
import { mobileWebType } from '../components/mobile-web-typography';
import { useI18n } from '../i18n';
import type { StoryDecisionAnswerInput } from './story-decision';

/**
 * 决策答复只有一套交互：Story 决策区与会话内提示共用，提交状态机留在各自的调用方。
 */
export function StoryDecisionAnswer({
  decision,
  disabled = false,
  busy = false,
  onCancel,
  onSubmit,
}: {
  decision: StoryDecision;
  disabled?: boolean;
  busy?: boolean;
  onCancel(): void;
  onSubmit(input: StoryDecisionAnswerInput): void;
}) {
  const { colors } = useMobileTheme();
  const { t } = useI18n();
  const [optionId, setOptionId] = useState('');
  const [replyPicked, setReplyPicked] = useState(false);
  const [response, setResponse] = useState('');
  // 只允许自由文本的决策没有可选项，回复就是唯一答案，直接展开。
  const replySelected = replyPicked || (!decision.options.length && decision.allowFreeText);
  const canSubmit = Boolean(optionId) || (replySelected && Boolean(response.trim()));

  const submit = () => {
    if (!canSubmit || disabled || busy) return;
    onSubmit({
      ...(optionId ? { optionId } : {}),
      ...(replySelected && response.trim() ? { response: response.trim() } : {}),
    });
  };

  return (
    <View style={styles.answer}>
      <View accessibilityRole="radiogroup" style={styles.choices}>
        {decision.options.map((option, index) => {
          const selected = optionId === option.id;
          return (
            <Pressable
              accessibilityLabel={option.label}
              accessibilityRole="radio"
              accessibilityState={{ disabled: disabled || busy, selected }}
              disabled={disabled || busy}
              key={option.id}
              onPress={() => { setOptionId(option.id); setReplyPicked(false); }}
              style={({ pressed }) => [
                styles.choice,
                { borderColor: 'transparent' },
                selected && { backgroundColor: colors.primarySoft, borderColor: colors.primary },
                (disabled || busy) && styles.disabled,
                pressed && styles.pressed,
              ]}
            >
              <View style={[styles.choiceIndex, { backgroundColor: selected ? colors.primary : colors.surfaceMuted }]}>
                <Text style={[styles.choiceIndexText, { color: selected ? colors.surface : colors.textMuted }]}>{index + 1}</Text>
              </View>
              <Text style={[styles.choiceLabel, { color: colors.text }]}>{option.label}</Text>
            </Pressable>
          );
        })}
        {decision.allowFreeText ? (
          <Pressable
            accessibilityLabel={t('stories.decisionReplyOption')}
            accessibilityRole="radio"
            accessibilityState={{ disabled: disabled || busy, selected: replySelected }}
            disabled={disabled || busy}
            onPress={() => { setOptionId(''); setReplyPicked(true); }}
            style={({ pressed }) => [
              styles.choice,
              { borderColor: 'transparent' },
              replySelected && { backgroundColor: colors.primarySoft, borderColor: colors.primary },
              (disabled || busy) && styles.disabled,
              pressed && styles.pressed,
            ]}
          >
            <View style={[styles.choiceIndex, { backgroundColor: replySelected ? colors.primary : colors.surfaceMuted }]}>
              <Text style={[styles.choiceIndexText, { color: replySelected ? colors.surface : colors.textMuted }]}>{decision.options.length + 1}</Text>
            </View>
            <Text style={[styles.choiceLabel, { color: colors.text }]}>{t('stories.decisionReplyOption')}</Text>
          </Pressable>
        ) : null}
      </View>
      {replySelected ? (
        <TextInput
          accessibilityLabel={t('stories.decisionFreeTextPlaceholder')}
          editable={!disabled && !busy}
          multiline
          onChangeText={setResponse}
          placeholder={t('stories.decisionFreeTextPlaceholder')}
          placeholderTextColor={colors.textPlaceholder}
          style={[styles.reply, { backgroundColor: colors.surface, borderColor: colors.border, color: colors.text }]}
          value={response}
        />
      ) : null}
      <View style={styles.buttons}>
        <Pressable
          accessibilityLabel={t('stories.decisionSubmit')}
          accessibilityRole="button"
          accessibilityState={{ disabled: disabled || busy || !canSubmit }}
          disabled={disabled || busy || !canSubmit}
          onPress={submit}
          style={({ pressed }) => [styles.submit, { backgroundColor: colors.primary }, (disabled || busy || !canSubmit) && styles.disabled, pressed && styles.pressed]}
        >
          {busy ? <ActivityIndicator color={colors.surface} size="small" /> : <Text style={[styles.submitText, { color: colors.surface }]}>{t('stories.decisionSubmit')}</Text>}
        </Pressable>
        <Pressable
          accessibilityLabel={t('stories.decisionCancel')}
          accessibilityRole="button"
          accessibilityState={{ disabled: disabled || busy }}
          disabled={disabled || busy}
          onPress={onCancel}
          style={({ pressed }) => [styles.cancel, { backgroundColor: colors.surfaceMuted }, (disabled || busy) && styles.disabled, pressed && styles.pressed]}
        >
          <Text style={[styles.cancelText, { color: colors.textMuted }]}>{t('stories.decisionCancel')}</Text>
        </Pressable>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  answer: { gap: 8, minWidth: 0 },
  choices: { gap: 2, minWidth: 0 },
  choice: { alignItems: 'center', borderRadius: 9, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: 10, minHeight: 44, paddingHorizontal: 8, paddingVertical: 4 },
  choiceIndex: { alignItems: 'center', borderRadius: 7, height: 22, justifyContent: 'center', width: 22 },
  choiceIndexText: { fontSize: mobileWebType.small, fontWeight: '500', lineHeight: mobileWebType.smallLine },
  choiceLabel: { flex: 1, fontSize: mobileWebType.small, lineHeight: mobileWebType.smallLine },
  reply: { borderRadius: 9, borderWidth: StyleSheet.hairlineWidth, fontSize: mobileWebType.small, lineHeight: mobileWebType.smallLine, minHeight: 60, paddingHorizontal: 10, paddingVertical: 8, textAlignVertical: 'top' },
  buttons: { flexDirection: 'row', gap: 8 },
  submit: { alignItems: 'center', borderRadius: 9, flexDirection: 'row', justifyContent: 'center', minHeight: 38, paddingHorizontal: 14 },
  submitText: { fontSize: mobileWebType.small, fontWeight: '500', lineHeight: mobileWebType.smallLine },
  cancel: { alignItems: 'center', borderRadius: 9, justifyContent: 'center', minHeight: 38, paddingHorizontal: 14 },
  cancelText: { fontSize: mobileWebType.small, fontWeight: '500', lineHeight: mobileWebType.smallLine },
  disabled: { opacity: 0.45 },
  pressed: { opacity: 0.65 },
});
